### ISSUE TITLE
[Feature]Xray

### ISSUE THREAD

**Issue by OrangesThighs** [McSnurtle/Project-Skyfall#136]
**Xray added to the server**
A clear and concise description of what you would like to see added.

**Infinite ores and stuff really easily**
Description of what problems the feature would solve, or cause for the player.

**Money**
What pre-existing systems this feature would interact with and how (if a removal suggestion, non applicable).

**
![image](https://github.com/user-attachments/assets/f8be8d04-48e0-43b8-a3d2-bd3cd7601bfc)
![image](https://github.com/user-attachments/assets/74106b2a-3e71-4887-9351-7b1c4da6a205)
**
Add additional screenshots or details to demonstrate your feature.

**Comment by McSnurtle** [comment]
Anti-Xray will be added in v1.1.2, possibly in v1.2
