### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by Nathaniel2011** [McSnurtle/Project-Skyfall#143]
**When was the crash**
When I load minecraft with the v1.2 update

**Crash Log**
[crash-2024-11-21_20.29.57-fml.txt](https://github.com/user-attachments/files/17853996/crash-2024-11-21_20.29.57-fml.txt)

```
Replace this text with the contents of the relevant crash report
found in /.minecraft/crash-reports/crash-year-month-day_forgeversion-fml.txt
```

**Server Version**
v1.2

**Screenshots (Optional)**
![image](https://github.com/user-attachments/assets/13908b7b-126c-41b6-bc0c-a8457df7982e)

**Additional Context (Optional)**
There is an issue with the curios dependency for the backpacks

**Comment by Nathaniel2011** [comment]
Update, if you go to the v1.2 changelog, and download curios-forge directly off of Modrinth, then you can join minecraft, and the server

**Comment by McSnurtle** [comment]
Re-releasing the update! Re-open if you get scammed again
