### ISSUE TITLE
[Crash]

### ISSUE THREAD

**Issue by OrangesThighs** [McSnurtle/Project-Skyfall#148]
**When was the crash**
A concise description of what you were doing before the game crashed
i download v1.3
**Crash Log**
If the log file is too long to attach in this issue, submit a link to a gist or similar.
```
[crash-2024-11-22_12.16.48-fml.txt](https://github.com/user-attachments/files/17873882/crash-2024-11-22_12.16.48-fml.txt)

Replace this text with the contents of the relevant crash report
found in /.minecraft/crash-reports/crash-year-month-day_forgeversion-fml.txt
```

**Server Version**
The current version of the server (the version described in the latest changelog, i.e. `v0.76.3`)
v1.3
**Screenshots (Optional)**
![image](https://github.com/user-attachments/assets/03d48bfe-a483-4e33-b7a1-169fa78df162)

**Additional Context (Optional)**
Any additional context to describe the crash.

**Comment by McSnurtle** [comment]
One off. Re-open if occurs again.
