### ISSUE TITLE
Cannot enter nether

### ISSUE THREAD

**Issue by Nathaniel2011** [McSnurtle/Project-Skyfall#157]
**Describe the bug**
When you go into the nether, you spawn above the nether roof on a platform, which immediately teleports you back to the nether because you're above the nether roof, which means because of earth's core, you "touched" bedrock or something like that.

**To Reproduce**
1. Go to the nether through use of Earth's Core
2. Get immediately teleported back to the overworld

**Server Version**
The current version of the server (the version described in the latest changelog, i.e. `v0.76.3`)
> v1.4-alpha

**Expected behaviour**
> You are supposed to spawn underneath the nether roof

**Screenshots (Optional)**
![image](https://github.com/user-attachments/assets/8c43c70d-3d4f-43f6-9599-59cf598d534c)
![image](https://github.com/user-attachments/assets/77f52df6-cf4c-4288-925d-c6228a4c0e18)

**Additional context (Optional)**
> bruh

**Comment by McSnurtle** [comment]
Oh dear, I believe I know the cause of this. Emergency fix being applied now!
