### ISSUE TITLE
[Bug] Natures compass search radius

### ISSUE THREAD

**Issue by brousmelly** [McSnurtle/Project-Skyfall#44]
**Describe the bug**
Natures compass only goes to a 10k block search radius instead of 50k (like it is set).

**To Reproduce**
1. Use a Nature's compass to search for a biome

**Server Version**
v0.61.3

**Expected behaviour**
The nature's compass reaches the configured 50k block search radius

**Comment by McSnurtle** [comment]
Issue with the mod, nothing I can do about it. Also, the 10k radius seems to be quite balanced, keeping the ultra rare biomes ultra rare.
