### ISSUE TITLE
[Crash] Mailbox issues

### ISSUE THREAD

**Issue by Nathaniel2011** [McSnurtle/Project-Skyfall#92]
**When was the crash**
I shift clicked 31 cobblestone into a mailbox, it automatically split, and my game crashed

**Crash Log**
[mailbox-crash.txt](https://github.com/user-attachments/files/17653195/mailbox-crash.txt)

```
Replace this text with the contents of the relevant crash report
found in /.minecraft/crash-reports/crash-year-month-day_forgeversion-fml.txt
```

**Server Version**
v0.65

**Screenshots (Optional)**

**Additional Context (Optional)**
Any additional context to describe the crash.

**Comment by McSnurtle** [comment]
This appears to be the same issue found in #132 , please continue this issue there.
